"use client";
import { ChangeEvent, useEffect, useState } from "react";
type Job = { id: string; status: string; result?: Record<string, unknown>; error?: string };
type Props = { onCompleted: (text: string) => void };
async function readJson(response: Response) { const raw = await response.text(); try { return JSON.parse(raw) as { job?: Job; error?: string }; } catch { throw new Error(`M?y ch? tr? v? HTTP ${response.status}. Vui l?ng t?i l?i trang r?i th? l?i.`); } }
export default function OcrPanel({ onCompleted }: Props) {
 const [job,setJob]=useState<Job|null>(null); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
 useEffect(()=>{ if(!job||["succeeded","failed"].includes(job.status))return; const timer=window.setInterval(async()=>{ const token=localStorage.getItem("novacard_token"); const r=await fetch(`/api/jobs/${job.id}`,{headers:{Authorization:`Bearer ${token||""}`,Accept:"application/json"},cache:"no-store"}); if(r.ok){const b=await readJson(r);if(b.job){setJob(b.job);if(b.job.status==="succeeded")onCompleted(String(b.job.result?.text||""));}}},1500);return()=>window.clearInterval(timer)},[job,onCompleted]);
 const optimize=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>{const image=new Image();image.onload=()=>{const scale=Math.min(1,1000/Math.max(image.width,image.height));const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));const ctx=canvas.getContext("2d");if(!ctx)return reject(new Error("Kh?ng th? x? l? ?nh"));ctx.drawImage(image,0,0,canvas.width,canvas.height);const data=canvas.toDataURL("image/jpeg",.65);if(data.length>950000)return reject(new Error("?nh v?n qu? l?n sau khi n?n. H?y ch?p l?i g?n danh thi?p."));resolve(data)};image.onerror=()=>reject(new Error("Kh?ng ??c ???c ?nh"));image.src=String(reader.result)};reader.onerror=()=>reject(new Error("Kh?ng ??c ???c ?nh"));reader.readAsDataURL(file)});
 const upload=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>10*1024*1024){setMessage("Ch? nh?n ?nh JPEG, PNG ho?c WebP t?i ?a 10MB");return}setBusy(true);setMessage("");try{const data=await optimize(file);const token=localStorage.getItem("novacard_token");const r=await fetch("/api/ocr/jobs",{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json",Authorization:`Bearer ${token||""}`},body:JSON.stringify({contentType:"image/jpeg",data})});const b=await readJson(r);if(!r.ok)throw new Error(b.error||"Kh?ng th? t?o OCR job");if(b.job)setJob(b.job)}catch(error){setMessage(error instanceof Error?error.message:"Upload th?t b?i")}finally{setBusy(false)}};
 return <section className="panel"><div className="panel-heading"><div><h2>S? h?a danh thi?p gi?y</h2><p>OCR Vi?t ? Anh ? H?n ch?y n?n, kh?ng ch?n m?n h?nh.</p></div></div><label className="upload-drop">{busy?"?ang t?i ?nh?":job?.status==="processing"?"?ang nh?n di?n?":"Ch?n ho?c ch?p ?nh danh thi?p"}<input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={upload} disabled={busy}/></label>{job&&<p className="form-message">Job {job.id.slice(0,8)}? ? {job.status}{job.status==="succeeded"&&" ? ?? ?i?n d? li?u v?o form b?n d??i"}</p>}{message&&<p className="form-message">{message}</p>}</section>;
}
