"use client";

import { ChangeEvent, useEffect, useState } from "react";

type Job = { id: string; status: string; result?: Record<string, unknown>; error?: string };

export default function OcrPanel() {
  const [job, setJob] = useState<Job | null>(null);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  useEffect(() => { if (!job || ["succeeded", "failed"].includes(job.status)) return; const timer = window.setInterval(async () => { const token = localStorage.getItem("novacard_token"); const response = await fetch(`/api/jobs/${job.id}`, { headers: { Authorization: `Bearer ${token || ""}` } }); if (response.ok) setJob((await response.json()).job); }, 1500); return () => window.clearInterval(timer); }, [job]);
  const upload = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; if (!["image/jpeg", "image/png", "image/webp"].includes(file.type) || file.size > 10 * 1024 * 1024) { setMessage("Chỉ nhận ảnh JPEG, PNG hoặc WebP tối đa 10MB"); return; } setBusy(true); setMessage(""); try { const data = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(new Error("Không đọc được ảnh")); reader.readAsDataURL(file); }); const token = localStorage.getItem("novacard_token"); const response = await fetch("/api/ocr/jobs", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token || ""}` }, body: JSON.stringify({ contentType: file.type, data }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Không thể tạo OCR job"); setJob(body.job); } catch (error) { setMessage(error instanceof Error ? error.message : "Upload thất bại"); } finally { setBusy(false); } };
  const confirm = async () => { if (!job) return; const token = localStorage.getItem("novacard_token"); const response = await fetch(`/api/ocr/jobs/${job.id}/confirm`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token || ""}` }, body: JSON.stringify({ fields: job.result }) }); setMessage(response.ok ? "Đã lưu liên hệ." : "Không thể lưu liên hệ."); };
  return <section className="panel"><div className="panel-heading"><div><h2>Số hóa danh thiếp giấy</h2><p>OCR Việt · Anh · Hàn chạy nền, không chặn màn hình.</p></div></div><label className="upload-drop">{busy ? "Đang tải ảnh…" : job?.status === "processing" ? "Đang nhận diện…" : "Chọn hoặc chụp ảnh danh thiếp"}<input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={upload} disabled={busy} /></label>{job && <p className="form-message">Job {job.id.slice(0, 8)}? ? {job.status}{job.status === "succeeded" && " ? kết quả đã sẵn sàng để review"}</p>}{job?.status === "succeeded" && <div className="ocr-review"><strong>Review trước khi lưu</strong>{Object.entries(job.result || {}).map(([key, value]) => <label key={key}>{key}<input defaultValue={String(value ?? "")} /></label>)}<button className="primary-cta" type="button" onClick={confirm}>Xác nhận và lưu</button></div>}{message && <p className="form-message">{message}</p>}</section>;
}
