"use client";

import { ArrowRight, CheckCircle2, LockKeyhole, Sparkles } from "lucide-react";
import { FormEvent, useState } from "react";

export default function AuthPage() {
  const [mode, setMode] = useState<"login" | "register">("login");
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [otp, setOtp] = useState(""); const [needsOtp, setNeedsOtp] = useState(false); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setMessage(""); try { const endpoint = mode === "register" ? "/api/auth/register" : "/api/auth/login"; const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Có lỗi xảy ra"); if (mode === "register") { setNeedsOtp(true); setMessage("Tài khoản đã tạo. Nhập OTP 000000 để xác thực bản demo."); } else { localStorage.setItem("novacard_token", data.token); window.location.href = "/dashboard"; } } catch (error) { setMessage(error instanceof Error ? error.message : "Có lỗi xảy ra"); } finally { setBusy(false); } };
  const verify = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { const response = await fetch("/api/auth/verify", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, otp }) }); if (!response.ok) throw new Error((await response.json()).error || "OTP không hợp lệ"); setMessage("Xác thực thành công. Bạn có thể đăng nhập."); setNeedsOtp(false); setMode("login"); } catch (error) { setMessage(error instanceof Error ? error.message : "OTP không hợp lệ"); } finally { setBusy(false); } };
  return <div className="app-shell"><div className="auth-layout"><div className="auth-hero"><a className="brand" href="/"><span className="brand-mark"><Sparkles size={16} /></span>NovaCard</a><div><p className="kicker">Nền tảng danh tính B2B</p><h1>Biến mỗi cuộc gặp thành một kết nối có giá trị.</h1><p>Danh thiếp số, hồ sơ thương hiệu và dữ liệu kết nối — trong một không gian chuyên nghiệp.</p><div className="hero-points"><span><CheckCircle2 size={17} /> Chia sẻ chỉ với một liên kết</span><span><CheckCircle2 size={17} /> Kiểm soát quyền riêng tư</span><span><CheckCircle2 size={17} /> Sẵn sàng cho mobile</span></div></div></div><div className="auth-card"><div className="auth-card-head"><span className="auth-icon"><LockKeyhole size={19} /></span><div><h2>{needsOtp ? "Xác thực tài khoản" : mode === "login" ? "Chào mừng trở lại" : "Tạo tài khoản NovaCard"}</h2><p>{needsOtp ? "Kiểm tra mã xác thực để tiếp tục." : "Bắt đầu xây dựng danh tính B2B của bạn."}</p></div></div>{needsOtp ? <form onSubmit={verify} className="form-stack"><label>Mã OTP<input value={otp} onChange={(e) => setOtp(e.target.value)} placeholder="000000" inputMode="numeric" required /></label><button className="primary-cta" disabled={busy}>{busy ? "Đang xác thực…" : "Xác thực tài khoản"}<ArrowRight size={17} /></button></form> : <form onSubmit={submit} className="form-stack"><label>Email công việc<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@company.com" required /></label><label>Mật khẩu<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Tối thiểu 8 ký tự" minLength={8} required /></label><button className="primary-cta" disabled={busy}>{busy ? "Đang xử lý…" : mode === "login" ? "Đăng nhập" : "Tạo tài khoản"}<ArrowRight size={17} /></button></form>}{message && <p className="form-message">{message}</p>} {!needsOtp && <p className="auth-switch">{mode === "login" ? "Chưa có tài khoản?" : "Đã có tài khoản?"} <button onClick={() => { setMode(mode === "login" ? "register" : "login"); setMessage(""); }}>{mode === "login" ? "Đăng ký miễn phí" : "Đăng nhập"}</button></p>}</div></div></div>;
}
