ALTER TABLE "Profile" ADD COLUMN IF NOT EXISTS "companyProfileUrl" TEXT;
ALTER TABLE "Profile" ADD COLUMN IF NOT EXISTS "projectsUrl" TEXT;
ALTER TABLE "Profile" ADD COLUMN IF NOT EXISTS "communityInfo" TEXT;
